### PR TITLE
Add AdditionalAddressLine to create/update customer

### PR DESCRIPTION
**Pull request by tvuotila**
Netvisor has an option to specify "AdditionalAddressLine" ([specification](https://netvisor.zendesk.com/hc/fi/articles/201993973-Resources-Customer-register-and-company-information#ankkuri4)) when updating or creating a customer.

PR implements the option.

### CODE REVIEW

**Comment by jpvanhal** [comment]
Could you also bump the marshmallow version? The parameters of `_deserialize` method were changed in 2.0.0rc1.

**Comment by tvuotila** [comment]
I fixed issues.

**Comment by tvuotila** [comment]
I added one more commit to fix new issues from stricter List validation in marshmallow version 2.0.0.

**Comment by jpvanhal** [comment]
Merged manually.

**Comment by jpvanhal** [comment]
This included in version 0.4.0.

**Pull request closed without merging**
